lab3/Models/ErrorViewModel.cs
using System;

namespace lab3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab3/Models/MyModelAnswer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace lab3.Models
{
    public class MyModelAnswer
    {
        public List<MyModelQuiz> answers = new List<MyModelQuiz>();
        public int correct = 0;
        private static MyModelAnswer instance = null;
        public static MyModelAnswer Instance
        {
            get
            {
                if (instance == null)
                    instance = new MyModelAnswer();
                return instance;
            }
        }
        public void Add(MyModelQuiz quiz)
        {
            if (quiz.Check())
                correct++;
            answers.Add(quiz);
        }
    }
}

lab3/Models/MyModelQuiz.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace lab3.Models
{
    public class MyModelQuiz
    {
        public int num1 { get; set; }
        public int num2 { get; set; }
        public double answer { get; set; }
        public string oper { get; set; }

        public MyModelQuiz()
        {
            Random rnd = new Random();
            num1 = rnd.Next(20);
            num2 = rnd.Next(20);

            string[] operands = { "+", "-", "*", "/" };
            oper = operands[rnd.Next(4)];
        }


        public bool Check()
        {
            double correct = default;
            switch (oper)
            {
                case "+":
                    correct = num1 + num2;
                    break;
                case "-":
                    correct = num1 - num2;
                    break;
                case "*":
                    correct = num1 * num2;
                    break;
                case "/":
                    correct = num1 / num2;
                    break;
            }
            if (correct == answer)
                return true;
            else
                return false;
        }
    }
}

lab3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using lab3.Models;

namespace lab3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab3/Controllers/MyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using lab3.Models;

namespace lab3.Controllers
{
    public class MyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult QuizView()
        {
            return View(new MyModelQuiz());
        }

        [HttpPost]
        public IActionResult QuizView(MyModelQuiz operation, string action)
        {
            if (ModelState.IsValid)
            {
                if (operation.Check())
                    MyModelAnswer.Instance.correct++;
                MyModelAnswer.Instance.answers.Add(operation);
            }
            else
            {
                ModelState.AddModelError("YourAnswer", "недопустимый формат ответа");
                return View(operation);
            }
            if (action == "Next")
                return View(new MyModelQuiz());

            return RedirectToAction("AnswerView");
        }
        public IActionResult AnswerView()
        {
            return View(MyModelAnswer.Instance);
        }
    }
}

lab3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div>
        <h1 class="display-4">Mockups</h1>
        <ul>
            <li>
                <a asp-controller="My" asp-action="QuizView"> Quiz </a>
            </li>
            <li>
                <a asp-controller="My" asp-action="AnswerView"> QuizResult </a>
            </li>
        </ul>
      
    </div>

lab3/Views/Shared/AnswerView.cshtml
@model lab3.Models.MyModelAnswer

@{
    ViewData["Title"] = "AnswerView";
}

<h1>Quiz results</h1>
<div>
    <h2>Right Answers @Model.correct out @Model.answers.Count </h2>
    <ul>
        @foreach (var m in Model.answers)
        {
            <li style="list-style-type: none;">
                @m.num1 @m.oper @m.num2 = @m.answer
            </li>
        }
    </ul>
</div>

lab3/Views/Shared/QuizView.cshtml
@model lab3.Models.MyModelQuiz

@{
    ViewData["Title"] = "QuizView";
}

<h1>Quiz</h1>
<div>
    <h2>@Model.num1  @Model.oper @Model.num2 = ?</h2>
    <form asp-antiforgery="true" asp-action="QuizView" asp-controller="My" method="post">
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <input name="answer" type="text">  <span asp-validation-for="answer"></span>
        <br />
        <input type="submit" value="Next" name="Action" style="border: 0.5px solid rgba(0, 0, 0, 0.56); padding: 4px 12px; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px; background: white; margin-top:10px;">
        <input type="submit" value="Finish" name="Action" style="border: 0.5px solid rgba(0, 0, 0, 0.56); padding: 4px 12px; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px; background: white; margin-top:10px;">
        <input style="display:none" name="num1" value="@Model.num1">
        <input style="display:none" name="oper" value="@Model.oper">
        <input style="display:none" name="num2" value="@Model.num2">
    </form>
</div>

lab3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Backend3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Backend3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Mockups</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Backend3 - <a asp-area="" asp-controller="Home"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>